learningequality/kolibri-design-system

lib/KIcon/index.vue

KIcon throughout Kolibri now depends on these. I just realized they weren't pushed to #9 when it was merged.

Added Icons

---

README.md

First pass rough draft.
Will revisit this later on but wanted to get it up for others' sake (and mine for easy review later on if needed)

Docs on yarn link

---

lib/KTextbox/index.vue
lib/buttons-and-links/KButtonGroup.vue
lib/keen/UiAlert.vue
lib/keen/UiAutocomplete.vue
lib/keen/UiAutocompleteSuggestion.vue
lib/keen/UiButton.vue
lib/keen/UiCloseButton.vue
lib/keen/UiPopover.vue
lib/keen/UiProgressCircular.vue
lib/keen/UiProgressLinear.vue
lib/keen/UiToolbar.vue
lib/keen/UiTooltip.vue
lib/keen/helpers/element-scroll.js
lib/keen/helpers/util.js
package.json
yarn.lock

1. Pull all of Keen used in Kolibri into KDS (also point Kolibri's use of KeenUI to KDS)
2. Fix issue with margin on KButtonGroup - @indirectlylit - I think that I might have lost the changes we discussed somewhere - but these fixed the issues with KButtonGroup where BottomBar buttons (which are displayed opposite of where they order in the DOM) were having issues with the margins using `first-child`

Big keen ui vendoring

---

docs/common/DocsPageTemplate/SideNav/NavSectionList.vue
lib/KBreadcrumbs.vue

single stylelint warnning fix from Kolibri isssue #6614
this is one single fix for #6614 for test

kbreadcrumbs_single_tag_remove

---

README.md

Are these instructions correct?
I couldn't get things running at first but when I skipped this command it worked

remove 'install' command

---

nuxt.config.js

Make debugging as easy as possible

add source maps in production

---

package.json

Hopefully this will make sure the latest is pulled from Github in Buildkite / Travis

Bump package version to 0.2.0-beta4 for new release

---

lib/KModal.vue

Fix Firefox strange behavior regarding adding unnecessary scrollbars (explained in more detail in comments)
Fixes https://github.com/learningequality/kolibri/issues/7163.

Modal scrollbars

---

.github/workflows/lint.yml
package.json

trying to add a linter using github actions

---

package.json

looks like there was already a beta4 release?
https://github.com/learningequality/kolibri-design-system/releases

update to beta 5

---

docs/assets/main.scss

|before|after|
|--|--|
|  ![2020-07-07 16 36 40](https://user-images.githubusercontent.com/2367265/86856032-5bf6ea00-c070-11ea-8257-15563ee97bc4.gif) | ![2020-07-07 16 36 22](https://user-images.githubusercontent.com/2367265/86856069-6b763300-c070-11ea-814e-489f8893d0c8.gif) |
thanks for the idea @micahscopes!

smooth scrollin'

---

docs/pages/snackbars.vue

didn't have a chance to review before we merged
here are some suggestions
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/88121454-96857a00-cb7a-11ea-9486-a229698d5e14.png) | ![image](https://user-images.githubusercontent.com/2367265/88121434-8a99b800-cb7a-11ea-87ec-39d50a9ddc2d.png)|

snackbars redux

---

lib/KModal.vue
lib/KRadioButton.vue
lib/buttons-and-links/buttonMixin.js
lib/styles/colorsDefault.js

fixes https://github.com/learningequality/kolibri-design-system/issues/12

cherry picks changes from Kolibri

---

docs/common/DocsAnchorTarget.vue
docs/common/DocsPageSection.vue
docs/pages/principles.vue

minor fixes

---

lib/buttons-and-links/KButton.vue

- Updated the icons' colors to be `$themeTokens.primary`
- Increased spacing between text and icon to be 8px.
Addresses #103 
|Before|After|
|--|--|
|![Screen Shot 2021-02-11 at 2 57 48 PM](https://user-images.githubusercontent.com/13563002/107709224-b8129400-6c79-11eb-9d93-d87f9e4b7819.png)|![Screen Shot 2021-02-11 at 10 28 32 PM](https://user-images.githubusercontent.com/13563002/107737604-9f29d300-6cb9-11eb-8853-d82dfdd72959.png)|

KButton - basic-link: add spacing between link and icons and change color of icons

---

.eslintrc.js
docs/common/DocsAnchorTarget.vue
docs/common/DocsExternalLink.vue
docs/common/DocsGithubLink.vue
docs/common/DocsInternalLink.vue
docs/common/DocsPageSection.vue
docs/common/DocsPageTemplate/Header.vue
docs/common/DocsPageTemplate/SideNav/NavLink.vue
lib/KCheckbox.vue
lib/KDropdownMenu.vue
lib/KIcon/index.vue
lib/KLabeledIcon.vue
lib/KModal.vue
lib/KRadioButton.vue
lib/KSwitch.vue
lib/KTextbox/index.vue
lib/KTooltip/Popper.vue
lib/buttons-and-links/KButton.vue
lib/buttons-and-links/KExternalLink.vue
lib/buttons-and-links/KIconButton.vue
lib/buttons-and-links/KRouterLink.vue
lib/grids/KFixedGrid.vue
lib/grids/KFixedGridItem.vue
lib/grids/KGrid.vue
lib/loaders/KCircularLoader.vue

Updates behavior of `default` and `required` props.
Refs:
* https://github.com/learningequality/kolibri/issues/7794
* https://github.com/learningequality/kolibri-design-system/pull/152#discussion_r575730153

update default and required props

---

docs/pages/principles.vue

These changes happened during the editing process for the design principles blog post. The changes are meant to add clarity and not change the original meaning and purpose of the principles. 
Based on https://blog.learningequality.org/how-we-built-equitable-design-principles-at-learning-equality-3ec18c3f8ffb

Adds grammatical tweaks and conceptual clarity to the design principles

---

README.md

Updates readme with additional information about deployment to Netlify

update deployment docs

---

CHANGELOG.md

v1.0.0 changelog

---

CHANGELOG.md

Adds https://github.com/learningequality/kolibri-design-system/pull/275/ to changelog

add #275 to changelog

---

lib/grids/KFixedGridItem.vue
lib/grids/KGridItem.vue
lib/grids/common.js

Adds `'auto'` alignment option to both fixed and responsive grid items
adds functionality in support of fixing https://github.com/learningequality/kolibri/issues/7650
**Before:**
```vue
<KFixedGrid numCols="4" debug>
<KFixedGridItem span="2">
مرحبا بالعالم
</KFixedGridItem>
<KFixedGridItem span="2">
Hello world
</KFixedGridItem>
</KFixedGrid>
```
**After**
```vue
<KFixedGrid numCols="4" debug>
<KFixedGridItem span="2" alignment="auto">
مرحبا بالعالم
</KFixedGridItem>
<KFixedGridItem span="2" alignment="auto">
Hello world
</KFixedGridItem>
</KFixedGrid>
```
Try creating grids with various text alignment options

support for 'auto' alignment in grid items

---

package.json

Update the package version to `v1.3.0`

---

jest.conf/index.js
lib/buttons-and-links/KRouterLink.vue
lib/buttons-and-links/__test__/KRouterLink.spec.js

Adds tests for `KRouterLink`
Addresses #304 
1. Run `yarn run test` in the terminal

Add `KRouterLink` tests

---

lib/keen/UiTextbox.vue
lib/keen/styles/variables.scss

#295: fixed the issue with Ktextbox error

---

docs/common/DocsAnchorTarget.vue
docs/common/DocsGithubLink.vue
docs/common/DocsPageTemplate/BranchLink.vue
lib/KModal.vue
lib/grids/KFixedGrid.vue
lib/grids/KFixedGridItem.vue
lib/grids/KGridItem.vue
lib/grids/common.js
lib/styles/theme.js
yarn.lock

Removes the use of loglevel in favour of just console.<fn>

Remove use of loglevel

---

.github/workflows/lint.yml

Updates the linting action to use yarn to ensure dependencies are pinned.

Update lint action to use yarn lockfile.

---

.github/workflows/lint.yml

Merges release v1.4.x branch into develop so that we have @rtibbles's GH actions lint check fix https://github.com/learningequality/kolibri-design-system/pull/352 available there.

Merge release v1.4.x into develop

---

CHANGELOG.md
docs/assets/main.scss
docs/pages/kresponsiveelement.vue
docs/pages/kresponsivewindow.vue
docs/pages/layout/index.vue
docs/tableOfContents.js

- Merges release-1.4.x into develop so that the latest documentation updates are available here (no conflicts were present except for one minor conflict in the changelog file)
- Adds updates introduced in https://github.com/learningequality/kolibri-design-system/pull/357 to the changelog

Merge release-1.4.x into develop

---

lib/styles/trackInputModality.js

adds input from search boxes to list of default elements so that search boxes will be focusable when tabbing through the kolibri interface
addresses issue [#9028](https://github.com/learningequality/kolibri/issues/9028): _Search box in embedded side panel is not highlighted when navigating from keyboard_
Please see corresponding [Kolibri PR](https://github.com/learningequality/kolibri/pull/9806) to test in Kolibri

add search input to default elements

---

lib/content/mixin.js

* Adds a finished event for KContentRenderer to address https://github.com/learningequality/kolibri/issues/9348

Add a finished event for KContentRenderer

---

lib/KDropdownMenu.vue

When a page first loads, clicking on a `KDropdownMenu` button causes the window to scroll to the top. This pr updates `KDropdownMenu` to fix this issue.
See issue mentioned here https://github.com/learningequality/kolibri/pull/9833#issuecomment-1322303903
Screen recording showing window scrolling to top of page on button click
https://user-images.githubusercontent.com/46411498/204568995-9b5b16cc-eed4-4d0b-bcc1-9248022ef0a2.mov
Screen recording showing button click after fixing
https://user-images.githubusercontent.com/46411498/204568842-ab5ced8c-e0f1-4d07-9c71-ab919d988ba0.mov
Please see corresponding Kolibri PR to test in Kolibri: https://github.com/learningequality/kolibri/pull/9877

Update to KDropdownMenu to fix window scrolling to top on first click

---

CHANGELOG.md

Just a little update to prepare the release branch

Remove changelog develop section from release branch

---

CHANGELOG.md
README.md

Updated develop branch to main branch in readme, along with respective links.
Issue #479 
- [#482]
- **Description:** Changed develop branch to main branch in Readme
- **Products impact:** Script Enhancement
- **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/479
- **Components:** none
- **Breaking:** no
- **Impacts a11y:** no
[#482]: https://github.com/learningequality/kolibri-design-system/pull/482

Updated Readme

---

CHANGELOG.md

Mark v3.0.0 section in the changelog
