learningequality/kolibri-design-system

- README.md
- lib/KBreadcrumbs.vue
- lib/KCheckbox.vue
- lib/KIcon/index.vue
- lib/KLabeledIcon.vue
- lib/KRadioButton.vue
- lib/KThemePlugin.js
- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/KButtonGroup.vue
- lib/buttons-and-links/KExternalLink.vue
- lib/buttons-and-links/KIconButton.vue
- lib/buttons-and-links/KRouterLink.vue
- lib/buttons-and-links/buttons.scss
~**WIP**~
** Ready for Review**
HOW TO:
- Checkout this branch locally,
- Checkout https://github.com/learningequality/kolibri/pull/6696 this branch locally
- `cd /path/to/design-system` and: `yarn link`
- `cd /path/to/kolibri` and remove the entry for `kolibri-design-system` from the `kolibri/core/package.json`
- `yarn link kolibri-design-system` then `yarn install`
Now you can run the devserver and will be using this branch :+1: 
Related Issue: https://github.com/learningequality/kolibri/issues/5900
Related Kolibri PR: https://github.com/learningequality/kolibri/pull/6696
- Remove 8px base margin on buttons.
- Create KButtonGroup - puts 8px margin on all `<a>` and `<button>` direct children of the `<span>` wrapper (with a CSS `.class > a, .class > button` selector).
... a lot of other …
> Buttons! KButtonGroup, KIconButton, etc

- lib/loaders/KCircularLoader.vue
This prop was removed but it is referenced in the file.
Was removed previously here: https://github.com/learningequality/kolibri-design-system/commit/6c34335e14efa40f426118fe5bde191e55b166c4
@indirectlylit do you recall if this was on purpose (and we should instead remove the reference) or should we keep this prop in?
> KCircularLoader `disableTransition` prop returns

- lib/buttons-and-links/KButtonGroup.vue
The overflow is unnecessary and hides the shadow. If it is not unnecessary we'll hear about it for sure but I haven't seen any issues.
> Fix for 0.14 to KButtonGroup

- lib/KTextbox/index.vue
Discussed on Slack that KTextbox validation messages will not show if that KTextbox was never focused or altered.
Adds `showInvalidText` prop w/ comments. Adjusted comment on `invalidText` prop as well to be more clear.
In Kolibri `kolibri/core/package.json` change:
`"kolibri-design-system": "github:nucleogenesis/kolibri-design-system-1#big-keen-ui-vendoring"`
to this:
`"kolibri-design-system": "github:nucleogenesis/kolibri-design-system-1#allow-forced-invalid-textbox"`
Then `yarn install --check-files` and you should be good to go testing this with Kolibri.
> Allow force showing invalidText in KTextbox

- README.md
- lib/loaders/KCircularLoader.vue
seeing lots of errors like this in current 0.14 Kolibri:
```
KCircularLoader.vue?7265:9 [Vue warn]: Property or method "disableTransition" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
found in
---> <KCircularLoader> at node_modules/kolibri-design-system/lib/loaders/KCircularLoader.vue
<TaskPanel> at kolibri/plugins/device/assets/src/views/ManageTasksPage/TaskPanel.vue
<TransitionGroup>
<ManageTasksPage> at kolibri/plugins/device/assets/src/views/ManageTasksPage/index.vue
<WithAuthMessage>
<KPageContainer> at node_modules/kolibri-design-system/lib/KPageContainer.vue …
```
> remove undefined prop reference

- lib/keen/styles/variables.scss
Mentioned here by @jonboiser https://github.com/learningequality/kolibri-design-system/issues/33
This line looks like it would load the wrong font in some cases.
I didn't actually replicate this - but it seems like this is where the problem lies.
To test in Kolibri - find your `kolibri/core/package.json` entry for `"kolibri-design-system"` to the value: `git@github.com:nucleogenesis/kolibri-design-system-1.git#keen-font`
Then `yarn install --force` and load up the Kolibri dev server.
> Keen font stack avoid system font superseding noto

- lib/keen/UiButton.vue
Fixes: https://github.com/learningequality/kolibri-design-system/issues/33
Now it is `cursor: pointer`
In Kolibri - a good place to have seen this was in the user profile dropdown.
> UiButton cursor:default -> cursor:pointer

- docs/common/DocsAnchorTarget.vue
- docs/common/DocsDoNot.vue
- docs/common/DocsShow.vue
- docs/pages/buttons.vue
- Added documentation for icon buttons 
- Added documentation for buttons that happen to have icons
- Allows for ability to hide "Do" and "Do not" blocks in `DocsDoNot.vue`
- Add component examples. I tried to indicate this as comments in code and bolded in the documentation page. I did attempt to make examples of the buttons myself but deleted because I am unsure whether the `KButton.vue` and/or `KIconButton.vue` files themselves need changes
https://docs.google.com/document/d/1ullAljzj7w813xpn2t6DUYzRKBLQsg7W4k6ahASLv6k/edit#
> Adding icons to button documentation

- docs/common/DocsPageTemplate/index.vue
netlify seems to add trailing slashes which don't appear locally
> clear trailing slashes

- .gitignore
- lib/KBreadcrumbs.vue
- lib/KLabeledIcon.vue
- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/KExternalLink.vue
- lib/buttons-and-links/KRouterLink.vue
- lib/buttons-and-links/buttons.scss
See regression issue here https://github.com/learningequality/kolibri/issues/7140
- Added `text` slot to `<KRouterLink>`
- Added `maxWidth` prop to `<KRouterLink>` and `<KLabeledIcon>`
- Added `.breadcrumbs-crumb-text` styling to handle text overflow
- Reduced specificity of global selectors styling the link text
> Fix breadcrumbs overflow

- lib/KDropdownMenu.vue
The download menu was drawing underneath slideshow content in Kolibri, as reported here: https://github.com/learningequality/kolibri/issues/7175
This makes sure that when active, the popover menu renders above the slideshow content (at a z-index of 12 in accordance with the material design spec).
> Ensure that `KDropdownMenu`'s popover menu has the correct z-index.

- package.json
You can't run KDS and Kolibri simultaneously locally because Kolibri web pack starts at 3000 - which is where nuxt runs.
This change will work until Kolibri builds 1000 plugins.
> change port to 4000 to avoid conflicts with kolibri in dev

- lib/KDropdownMenu.vue
I saw a bunch of console logs like this all over in Kolibri:
```
vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "zIndex". Expected Number with value 12, got String with value "12".
found in
---> <UiPopover> at design-system/lib/keen/UiPopover.vue
<KDropdownMenu> at design-system/lib/KDropdownMenu.vue
<CoreTable> at kolibri/core/assets/src/views/CoreTable.vue
<UserTable> at kolibri/plugins/facility/assets/src/views/UserTable.vue
<PaginatedListContainer> at kolibri/core/assets/src/views/PaginatedListContainer.vue
<KPageContainer> at design-system/lib/KPageContainer.vue
<UserPage> at kolibri/plugins/facility/assets/src/views/UserPage/index.vue
<CoreBase> at kolibri/core/assets/src/views/CoreBase/index.vue
<Root>
```
Just need to use the `:` on the prop so the …
> z-index needs a Number and refuses to parseInt() for you

- lib/buttons-and-links/KButton.vue
The logic for "what color should the icon be" for a KButton w/ an icon or iconAfter prop did not account for all options.
Spin this up and add this to a page you can view in KDS to test it:
```
<label>Primary & Raised - White Text</label>
<KButton :primary="true" icon="facility" text="Facility" appearance="raised-button" />
<br /><br />
<label>Secondary & Raised - Text (Black) Text</label>
<KButton :primary="false" icon="facility" text="Facility" appearance="raised-button" />
<br /><br />
<label>Primary & Flat - Primary (Purple) Text</label>
<KButton :primary="true" icon="facility" text="Facility" appearance="flat-button" />
<br /><br />
<label>Secondary & Flat - Text (Black) Text</label>
<KButton :primary="false" icon="facility" text="Facility" appearance="flat-button" />
<br /><br /> …
```
> Kbutton icon color

- lib/KBreadcrumbs.vue
- lib/KLabeledIcon.vue
- lib/buttons-and-links/KExternalLink.vue
Somewhat (for now) related Kolibri PR: https://github.com/learningequality/kolibri/pull/7360 - somewhat related in that the fixes below don't depend on that PR and that PR doesn't (yet) depend on this one.
- 03ce517 Fixes: https://github.com/learningequality/kolibri-design-system/issues/81 - where KLabeledIcon margins were off in RTL languages.
- 29ba2b9 Fixes: https://github.com/learningequality/kolibri-design-system/issues/25 - KExternalLink now securely opens in a new tab
- f5a35d5 Fixes: https://github.com/learningequality/kolibri/issues/7355 - Breadcrumbs without underlines
- 3ce9698 Fixes: https://github.com/learningequality/kolibri/issues/7378 - KLabeledIcon margins/sizing wrap issue
> Batch of bug fixes

- docs/pages/buttons.vue
- docs/pages/icons/IconBlock.vue
- lib/KDropdownMenu.vue
- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/KIconButton.vue
Implements examples for the Buttons based on @jtamiace 's initial documentation docs for buttons and the feedback in the comments.
Includes code changes surrounding tooltips on KIconButtons and `icon` prop alignment in KButton.
Fixes https://github.com/learningequality/kolibri-design-system/issues/69
> Button examples

- lib/KLabeledIcon.vue
- package.json
Bump so that Kolibri pulls the proper latest and doesn't use cached version.
> bump to beta6

- lib/buttons-and-links/KExternalLink.vue
Unexpected side effect of opening KExternalLinks in a new tab is fixed.
Related to https://github.com/learningequality/kolibri/issues/7482 and https://github.com/learningequality/kolibri/issues/7480
> KExternalLink to *not* open in new tab (for now)

- lib/KIcon/iconDefinitions.js
- lib/KIcon/index.vue
- lib/buttons-and-links/KIconButton.vue
- package.json
- yarn.lock
Fixes https://github.com/learningequality/kolibri-design-system/issues/109
Adds the missing icons:
- KDS Token: `sidebar` - https://material.io/resources/icons/?search=vertical_split&style=baseline
- KDS Token: `email` - https://material.io/resources/icons/?search=mail&icon=mail_outline&style=baseline
- KDS Token: `add` - https://material.io/resources/icons/?search=add&icon=add_circle_outline&style=baseline
Also:
- Bumps the version of KDS to `v0.2.2-beta`.
> Adds `add` icon `add_circle_outline`

- docs/common/DocsColorBlock.vue
- docs/pages/KSwitch.vue
- docs/pages/colors.vue
- docs/pages/errors/index.vue
- docs/pages/index.vue
- docs/pages/layout/index.vue
- docs/pages/menus/index.vue
- docs/pages/textfields/index.vue
This PR changes nearly all instances of internal and external links to use props instead of slots, from this form:
```html
Follow the <DocsExternalLink href="https://material.io/design">
Material design guidelines
</DocsExternalLink>.
```
to this form
```html
Follow the <DocsExternalLink text="Material design guidelines" href="https://material.io/design" />.
```
This has two advantages:
A) the previous form causes undesirable underline behaviors:
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/94084633-c8090480-fdba-11ea-847f-6353df465a94.png)  | <img width="473" alt="image" src="https://user-images.githubusercontent.com/2367265/94084498-8aa47700-fdba-11ea-9170-013d03f17203.png"> |
B) The code is more concise.
Note while possibly desirable for …
> update link usage

- lib/buttons-and-links/KIconButton.vue
@nucleogenesis Please see https://github.com/learningequality/studio/pull/2280
> KIconButton - Use "zIndex" property instead of "style" in UiTooltip

- lib/KIcon/iconDefinitions.js
- package.json
Addresses: https://www.notion.so/learningequality/Copy-to-clipboard-icon-in-toolbar-should-be-outline-not-filled-5fcdf036bc51441697fc29b8cfcae257 because I put the wrong icon.
Also bumps the beta version in package.json to ensure Studio works from the correct code and doesn't use a cached version.
> Clipboard icon should be outline not baseline

- lib/buttons-and-links/KIconButton.vue
Fixes
```
Invalid prop: type check failed for prop "zIndex". Expected Number with value 24, got String with value "24".
```
> Fix invalid property type check

- package.json
Gets #122 in for improved Studio debugging (no more console spam).
> Bump version 0.2.2-beta4 

- docs/pages/icons/index.vue
- nuxt.config.js
adds a section of documentation on how to use the icons in rst docs, along with direct-copy ability:
> add documentation about using icons in rst

- lib/buttons-and-links/KExternalLink.vue
**Summary:**
- Added boolean prop `openInNewTab` to `KExternalLink`
- Added `:target` to anchor tag in `<template>` to open up new tab if `openInNewTab` is given `true`
Fixes #94 
**Testing:**
- Tested with Chrome on MacOSX, but not yet with other versions of Kolibri.
> Add boolean prop, 'openInNewTab' to KExternalLink

- lib/buttons-and-links/KRouterLink.vue
Added `replace` prop to `KRouterLink` by making `replace` accessible within `<router-link>` component.
Addresses #85
> Add `replace` prop to KRouterLink

- lib/buttons-and-links/KRouterLink.vue
Updated `required=false` to `default=false` - [the issue that was not caught with the linter](https://github.com/learningequality/kolibri-design-system/pull/152#discussion_r575730153).
> Fix default=false on boolean prop

- lib/buttons-and-links/KExternalLink.vue
@nucleogenesis - it's all fixed now! Here is a summary of what was updated:
|English text in English|Arabic text in Arabic|
|--|--|
|![Screen Shot 2021-01-05 at 9 57 34 AM](https://user-images.githubusercontent.com/13563002/103700650-a262ce00-4f59-11eb-862a-40b1bc08be60.png)|![Screen Shot 2021-01-05 at 1 35 25 PM](https://user-images.githubusercontent.com/13563002/103701510-fd48f500-4f5a-11eb-8419-499d4a722ea0.png)|
|Now: English text in Arabic|(Previously: English text in RTL)|
|--|--|
|![Screen Shot 2021-01-05 at 1 06 08 PM](https://user-images.githubusercontent.com/13563002/103700631-9bd45680-4f59-11eb-9a07-e17db1b55e78.png)|![Screen Shot 2021-01-05 at 9 56 58 AM](https://user-images.githubusercontent.com/13563002/103700717-b73f6180-4f59-11eb-8669-7090b2ef7ef8.png)|
|No margins, no …
> <KExternalLink> final fixes for icons and margins

- docs/pages/glossary/index.vue
---
name: Pull Request
about: Create a pull request
title: "Add anchor tags to glossary"
labels: 'docs, Q1 Milestone'
assignees: ''
---
Adds anchor links on the glossary page to each individual term 
Fixes #146 
BEFORE
AFTER
Based on the Icons page, I similarly created a method to dynamically add anchor links based on the term, and used the `<DocsAnchorTarget/>` component to handle the styling.
> Add anchor links to individual glossary terms

- lib/buttons-and-links/KIconButton.vue
This PR re-adds a minWidth value, which prevents the "squished" effect that is seen in Studio with some browser window resizes, especially at small sizes (~600px) in the tree views
> Added minWidth to prevent squished/oval effect in KIconButton

- README.md
- docs/assets/main.scss
- docs/common/DocsFilter/utils.js
- docs/common/DocsFilter/utils.spec.js
- docs/common/DocsGithubLink.vue
- docs/common/DocsLibraryLink.vue
- docs/common/DocsPageTemplate/SideNav/index.vue
- docs/common/DocsPageTemplate/jsdocs/EventsTable.vue
- docs/common/DocsPageTemplate/jsdocs/MethodsTable.vue
- docs/common/DocsPageTemplate/jsdocs/PropsTable.vue
- docs/common/DocsPageTemplate/jsdocs/SlotsTable.vue
- docs/common/DocsPageTemplate/jsdocs/styles.scss
- docs/pages/KButton.vue
- docs/pages/KButtonGroup.vue
- docs/pages/KCheckbox.vue
- docs/pages/KExternalLink.vue
- docs/pages/KIconButton.vue
- docs/pages/KRouterLink.vue
- docs/pages/KSwitch.vue
- docs/pages/buttons.vue
- docs/plugins/load-common-components.js
- docs/tableOfContents.js
- lib/KCheckbox.vue
- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/KButtonGroup.vue
- lib/buttons-and-links/KExternalLink.vue
- lib/buttons-and-links/KIconButton.vue
- lib/buttons-and-links/buttonMixin.js
Adds documentation for library components:
* `KButton`
* `KRouterLink`
* `KExternalLink`
* `KButtonGroup`
* `KIconButton`
Adds a new 'keywords' property to the table of contents to allow filtering by related terms. For example:
```js
new Page({
path: '/KButton',
title: 'KButton',
isCode: true,
keywords: ['button', 'link'],
}),
```
Adds a new `DocsLibraryLink` component to allow easy cross-linking. For example:
```vue
<DocsLibraryLink page="KExternalLink" /> is used to create standard <code>&lt;a&gt;</code> tags with an <code>href</code> attribute.
```
> Button docs

- docs/pages/menus/index.vue
This PR adds detail to the Menus page. If a menu will touch the edge of the browser's screen when opened, we should add an offset of 8px. 
Addresses https://github.com/learningequality/kolibri-design-system/issues/120
> Adds menu offset guideline

- lib/keen/UiTextbox.vue
- lib/styles/colorsDefault.js
This is a draft for now - this should not be merged until KSelect is also available in KDS and has the same or similar styles applied.
Fixes #124
Fixes #167 
- Gray #e9e9e9 background on KTextbox
- CSS changes to align things roughly like the sample field https://material.io/components/text-fields
- Changed the value given to the `translate()` CSS function to ensure the label is centered (original value pushed the label to the baseline)
- Add a `&nbsp;` empty div fallback for the part of the DOM flow where the error/help message would show. A counter shows on the same horizontal line but is `position: absolute;` so when there is no help/error text, subsequent elements are closer to the previous one than they ought to be and they look squished. 
I took this first screenshot w/ a delay …
> Material background on KTextbox

- lib/KCheckbox.vue
Fixes #35 
I also thought that the `v-if-else` block there was weird because if I gave both a slot and a label it would show neither - so I picked one to be the override. 
Now if you give a slot and a label you'll see what is passed to the slot - if you don't give a slot it's expected you give a label.
| Before |
|---|
| ![screenshot-localhost_8000-2021 03 18-14_44_52](https://user-images.githubusercontent.com/6356129/111701778-86509800-87f8-11eb-8c23-a6e8d4853915.png) |
| After |
|---|
| ![screenshot-localhost_8000-2021 03 18-14_39_20](https://user-images.githubusercontent.com/6356129/111701679-67520600-87f8-11eb-8df7-15ab64e73a6b.png) |
1. `yarn link kolibri-design-system` in your `kolibri` local repo
2. Checkout this PR in `kolibri-design-system` repo
3. Run Kolibri dev server
4. Find …
> KCheckbox description prop, simplified logic around slot vs label showing

- lib/KLabeledIcon.vue
- lib/buttons-and-links/KRouterLink.vue
Fixes the text-wrapping that occurs from webkit/Safari in `KLabeledIcon` and `KRouterLink`. PR in Kolibri addresses the specific issue that is found in the user dropdown menu for "Change language" option.
Addresses learningequality/kolibri#7378
|`KLabeledIcon` fix for "Sign out"|
|--|
|![Screen Shot 2021-03-16 at 9 04 50 PM](https://user-images.githubusercontent.com/13563002/111537048-3a362280-8728-11eb-854e-8adfb2b73cd4.png)|
|`KRouterLink` Before|`KRouterLink` After|
|--|--|
|![Screen Shot 2021-03-16 at 9 05 57 PM](https://user-images.githubusercontent.com/13563002/111537053-3b674f80-8728-11eb-91dd-4f282d5c4ce0.png)|![Screen Shot 2021-03-16 at 9 06 14 PM](https://user-images.githubusercontent.com/13563002/111537054-3bffe600-8728-11eb-86fd-b1047b6c768d.png)|
|`KLabeledIcon` …
> Fixes Safari text-wrapping in KLabeledIcon and KRouterLink

- docs/plugins/load-lib-components.js
- lib/styles/trackInputModality.js
Track input modality on documentation pages because `KThemePlugin` used by KDS components in documentation examples needs this information to be able to decide if a keyboard focus ring should be displayed (input modality information is used only to inform KDS components, not the documentation pages themselves).
See commit messages for details.
Addresses #70
Because I made some updates to a code that is used in projects that import KDS, I also checked that there are no changes in Kolibri by linking the updated KDS package locally to Kolibri:
1. Use the keyboard to navigate documentation
I added a new option to the `trackInputModality` that allows us to not disable the default focus ring and then imported `trackInputModality` to documentation pages using this new setting so that there is a …
> Show proper keyboard focus ring in KDS examples in documentation

- docs/common/DocsPageTemplate/SideNav/index.vue
Persist side nav bar scroll position and filter state using `Window.sessionStorage`, which should be per-tab.
fixes https://github.com/learningequality/kolibri-design-system/issues/182
|--|--|
| ![2021-03-26 16 45 54](https://user-images.githubusercontent.com/2367265/112703127-13c46580-8e53-11eb-958c-ba494a8923a4.gif) | ![2021-03-26 17 05 20](https://user-images.githubusercontent.com/2367265/112703846-9ea65f80-8e55-11eb-9d9e-225fdedb5160.gif) |
Experiment with navigation through the design system and see how it feels
* Persists changes to state
* Loads state on `mounted`
* Tries to keep the nav hidden until state has been loaded but doesn't always work as intended
* There's a brief flash during page load
> persist nav state

- lib/buttons-and-links/KIconButton.vue
reverts one change in https://github.com/learningequality/kolibri-design-system/pull/165 which caused many prop warnings
fixes https://github.com/learningequality/kolibri-design-system/issues/86
upgrade kolibri and verify that prop validation errors are gone
> revert prop change

- lib/utils/pluginMediator.js
* Stops trying to load css files that don't exist
* This can happen in hot module replacement mode when CSS files are bundled into Javascript
1. Run Kolibri with this patch on KDS, with `devserver-hot` and check that the EpubRenderer now properly loads.
> Don't try to load non-existent css files

- docs/pages/buttons.vue
Update text in the ["Placement" section of buttons documentation](https://design-system.learningequality.org/buttons/#placement) (the second item of the list) from "Left-aligned **a** the bottom of page forms" to "Left-aligned **at** the bottom of page forms".
> Fix typo in buttons documentation

- lib/styles/trackInputModality.js
Fixes https://github.com/learningequality/kolibri/issues/7974
*Kolibri*
- `yarn link` the design system (see [KDS Readme](https://github.com/learningequality/kolibri-design-system/) for help there)
- Run Kolibri and test that the outline comes up when you're keyboard navigating but does not come up when you're hovering with a mouse.
*KDS*
- `yarn dev` the KDS documentation (or just use the Preview link below at the GIthub Actions)
- Make sure that you see the keyboard navigation box when navigating by keyboard there.
[This commit is where the bug was introduced.](https://github.com/learningequality/kolibri-design-system/commit/e26893fcc6d970c11ca86b771cdc24658892c569) @MisRob undoing this fixes the issue - was there some other effect you expected to see when making this change?
[Reverts …
> Fix keyboard outline in Kolibri - no longer showing unless keyboard navigating

- docs/pages/modals/index.vue
- docs/pages/pageheader/index.vue
I messed up my local git somehow... reposting [this PR](https://github.com/learningequality/kolibri-design-system/pull/176) here
Adds guidelines to not use verbs ending in "-ing" on page titles and modal titles because they give the false impression that a task is in progress. Added to Page headers and Modals pages
Addresses https://github.com/learningequality/kolibri-design-system/issues/92
| Before  | After |
| ------------- | ------------- |
| <img width="736" alt="Screen Shot 2021-03-01 at 4 27 04 PM" src="https://user-images.githubusercontent.com/6668144/109577844-22fe0080-7aab-11eb-925c-8f6718c06a28.png"> | <img width="746" alt="Screen Shot 2021-03-01 at 4 26 02 PM" src="https://user-images.githubusercontent.com/6668144/109577861-2b563b80-7aab-11eb-98c6-e082b7a86809.png"> |
| Before …
> Adds imperative verb guidance to modals and page headers

- lib/keen/UiTextbox.vue
[I did this](https://github.com/learningequality/kolibri-design-system/pull/139/commits/bf4fbd1fa57550ae12b39215d767e8eb41bed524#diff-687c5d9eca13195cf34fba3cf61e97418d9ac5f1ea6a43035523bcffd6dfd37cL502) in a follow-up commit and didn't realize it before merging. How and why this happened are beyond me.
Puts a gray background on KTextbox per Material guidance.
> KTextbox with gray material background

- lib/content/mixin.js
Removes the `download_url` property from the file map in `mixin.js` for the `KContentRenderer` to mirror the changes in learningequality/kolibri#8005.
No screenshot needed, but the `fileValidator` method for `KContentRenderer` was returning a console error.
1. Open an exercise in a Khan Academy lesson.
2. Open the console and check to see that there are no errors.
No
> Remove download_url property

- README.md
- lib/KIcon/iconDefinitions.js
- package.json
- utils/extractRstIcons.js
- utils/precompileSvgs/index.js
- utils/precompileSvgs/precompilationDiff.js
This PR adds more information about the icons upgrades process to documentation and also adds a utility for printing differences in public KDS icons after running the precompilation script to help with tracking updates.
Precompilation diff displayed in my terminal after upgrading Google Material Icons and running `yarn run precompile-svgs`:
Please read the documentation updates and then follow **Example: Upgrading Google Material Design Icons** to check the before/after icons precompilation diff reporting for yourself.
We now have even more logic built around parsing [iconsDefinitions.js file](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KIcon/iconDefinitions.js) with regexes (see [this commentary](https://github.com/learningequality/kolibri-design-system/blob/ …
> Report KDS public icons diff after precompilation and add more information about icons upgrade to README

- .github/ISSUE_TEMPLATE/issue_template.md
- .github/pull_request_template.md
Updates the PR template with a section for the PR-writer to add in the `changelog` and also to manually point the most recent version of KDS to the Kolibri `develop` branch.
Addresses #247
We will need to make sure that there is clear documentation about how to add to the `changelog` (this may be something we can add to the PR template in the future so that anyone can just access it). For now, we can just tell folks how to do it (internally). Same goes with how to point Kolibri to the right branch of KDS. 
Doesn't need to be said, but all feedback appreciated, of course.
> Update PR template for KDS release process

- .gitignore
- lib/KTextbox/index.vue
- lib/keen/UiTextbox.vue
Test failures in a [Studio PR](https://github.com/learningequality/studio/pull/3235) indicated a regression in `KTextbox`. Looking at the code, I surmised the issue resulted from using `autofocus` along with how the invalid state is triggered.
| Initial state before | Initial state after | Error state after |
| --- | --- | --- |
| ![Screenshot from 2021-08-31 13-12-09](https://user-images.githubusercontent.com/819838/131575338-57d26ab0-25d1-4ed2-b89f-98e49a2a90cd.png)  | ![Screenshot from 2021-08-31 14-03-44](https://user-images.githubusercontent.com/819838/131575708-ed237fae-5b6f-4e71-a8ac-0aa28278505c.png) | ![Screenshot from 2021-08-31 14-02-56](https://user-images.githubusercontent.com/819838/131575635-8fd6626d-495a-45c2-8a1d-14e0b5a14cdc.png) |
1) Link KDS into Studio-- you may have …
> Fix textbox autofocus triggering invalid message

- README.md
Clarify that KDS is not intended for stand-alone use, and that plugins should not import it directly.
If we start publishing to NPM, this will hopefully help dissuade casual users from trying to use it in their own work.
> clarify usage intent

- CHANGELOG.md
- lib/KModal.vue
* Updates `KModal`'s `size` prop to take a precise width in pixels, in addition to existing `'small'`, `'medium'`, and `'large'` strings.
* Updates changelog, including reference to https://github.com/learningequality/kolibri-design-system/pull/278
Helps address https://github.com/learningequality/kolibri/issues/8636
In this case, 'medium' was still too small but 'large' was too big.
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/143077464-50e97354-741a-4843-958f-7733e43d4103.png) | ![image](https://user-images.githubusercontent.com/2367265/143077394-cf3d3fbb-8a5d-42c2-bd78-1237cc31343a.png) |
| ![image](https://user-images.githubusercontent.com/2367265/143077511-4aab4a68-65f0-4669-a9a8-aad16a5cc7ec.png) | …
> allow KModal to take a precise width in pixels

- docs/pages/index.vue
Adds a link to the docs for the [Figma file](https://www.figma.com/file/JPL94qI0O1s9FOHV92OeCmpS/Kolibri-Design-System?node-id=0%3A1) containing the patterns, colors, branding, etc. for KDS.
N/A
1. Start the documentation server
2. See change in docs on home page
> Add link to KDS figma file

- lib/buttons-and-links/KButtonGroup.vue
adds vertical padding when buttons wrap to the next line. This is partly for example or future reference unless we decide to try and squeeze it in to 0.15
fixes https://github.com/learningequality/kolibri-design-system/issues/84
refs:
* https://github.com/learningequality/kolibri/pull/8946#pullrequestreview-835383387
* https://learningequality.slack.com/archives/CB37UM23A/p1639690847424500
|--|--|
| ![2021-12-17 11 04 34](https://user-images.githubusercontent.com/2367265/146573462-4eb45c4b-98f2-4f38-a043-a75f4dc0ba67.gif) | ![2021-12-17 11 04 01](https://user-images.githubusercontent.com/2367265/146573473-e87d6d82-61b4-45fe-8411-065c36620a19.gif) |
update kolibri with this change and check for regressions
* Adds a wrapper div to each element added in the lost using a …
> render function for handling vertical button wrap

- CHANGELOG.md
- lib/styles/trackInputModality.js
Set modality to keyboard only when TAB key is pressed when tracking input modality.
Fixes https://github.com/learningequality/kolibri/issues/8786
Follow test instructions in https://github.com/learningequality/kolibri/pull/8971
I added a whitelist of keys that should change the modality to keyboard. Currently, only TAB key is in the whitelist. Any other keys don't change the modality to keyboard.
One thing to be cautious about is that many keys that used to change the input modality to keyboard won't change it anymore. I haven't noticed any problems so far. Can you think of any situations where we might need to display the focus ring for keyboard navigation when NOT using TAB/SHIFT+TAB?
> Can't think of any use case on the top of my head, but will do some searching and chime it if I find …
> Set modality to keyboard only when TAB is pressed

- CHANGELOG.md
- docs/pages/kbreadcrumbs.vue
- docs/tableOfContents.js
- lib/KBreadcrumbs.vue
|  | Before | After |
| - | -------- | ------- |
| KDS docs | ![doc-breadcrumbs-vertical-align-before](https://user-images.githubusercontent.com/13509191/147820418-cf56c266-ccf5-4572-b3e8-f53ff7ce678d.png) | ![doc-breadcrumbs-vertical-align-after](https://user-images.githubusercontent.com/13509191/147820422-8b28038c-b18b-4f4b-a8c4-215a3de07248.png) |
|  | Before | After |
| - | -------- | ------- |
| KDS docs | ![doc-breadcrumbs-space-before](https://user-images.githubusercontent.com/13509191/147820491-3641679a-4fc7-4b90-9076-38ca0f355d79.png) | ![doc-breadcrumbs-space-after](https://user-images.githubusercontent.com/13509191/147820497-df8b4137-63ab-4cd1-b632-b21a44a81efd.png) |
| Kolibri | ![kolibri-breadcrumbs-before](https://user-images.githubusercontent.com/13509191/147820983-5ea39ef9- …
> A new documentation page and layout fixes for KBreadcrumbs

- lib/content/mixin.js
Add navigateTo listener in KContentRenderer mixin for HTML5 hashi work.
Please see this [kolibri PR for extensions to the navigateTo work](https://github.com/learningequality/kolibri/pull/8134).
> Add navigateTo listener in KContentRenderer mixin for HTML5 hashi work

- lib/KIcon/iconDefinitions.js
Updates the configuration file so that the Exercise icon flips when in RTL.
- Checkout this branch locally
- Link it to your Kolibr
- Check that the icon flips in RTL
Fixes #301
> Exercise icon flipped in rtl

- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/__tests__/KButton.spec.js
Adds initial unit tests for some KButton behavior.
Does not test `buttonMixin` behavior as that should be tested separately. This impacts other components and having tests for buttonMixin might be a better next step than any other items in the `buttons-and-links` directory.
- What behavior in KButton that is not defined in the buttonMixin should I test that isn't covered here?
Addresses #303
> KButton Tests

- CHANGELOG.md
- lib/KModal.vue
- lib/__test__/KModal.spec.js
1. Adds tests for `KModal`
2. Changes the way the error message (for accessibility) is handled by moving that responsibility to the parent
3. Adds the 4 tests completed to the `changelog.md`
Fixes #305
1. Run `yarn run test` in the terminal
No
> Add tests for `KModal`

- lib/KDropdownMenu.vue
- lib/keen/UiMenu.vue
- lib/keen/UiMenuOption.vue
- lib/styles/trackInputModality.js
- yarn.lock
This PR adds tab navigability for KDropdownModal. Currently, a user cannot use keyboard navigation to enter into the dropdown.
Fixes #178 
BEFORE
AFTER
1. Use the tab key to navigate to a dropdown menu
2. Use the enter key to open the dropdown
3. The focus should be directed to the first item in the menu
4. Using the tab key should direct you down each item in the menu, and then a double-tab at the end should bring you back to the first element
5. Using escape key when you are inside the menu should close the menu, and bring the focus back to the dropdown menu button
Any feedback for general code improvement (and if I'm using some of the existing KDS patterns correctly) or about how this affects other components that I might not be thinking of would be very helpful.
Also, @jtamiace / …
> Kdropdown keyboard navigation

- lib/buttons-and-links/KButtonGroup.vue
Catches an edge case when a KButtonGroup has no Buttons inside it.
1. Create a KButtonGroup with nothing in it
2. Confirm it can render without errors.
3. Profit!
> Handle empty KButtonGroups

- CHANGELOG.md
- lib/keen/UiToolbar.vue
This PR updates the base UiToolbar layout to allow for inline navigation tabs
Supports implemention of Kolibri # 9274
Example from kolibri update 
Please see [corresponding Kolibri PR](https://github.com/learningequality/kolibri/pull/9496)
> Allow for new 'nav' slot inline in the toolbar

- CHANGELOG.md
- docs/pages/kcheckbox.vue
- lib/KCheckbox.vue
- lib/__tests__/KCheckbox.spec.js
- Previously, the default slot content was wrapped in `<div>`, making the checkbox inaccessible when label's content is provided via the default slot. This PR fixes it by replacing `<div>` with `<label>` (this also makes using the default slot consistent with using the `label` property)
- Organizes `KCheckbox` documentation page and adds some examples of how to use labels
Addresses #347 
- No visual changes in products
- `KCheckbox` documentation
- before: https://design-system.learningequality.org/kcheckbox/
- after: https://deploy-preview-351--kolibri-design-system.netlify.app/kcheckbox/
- Please follow the steps to test in Kolibri's corresponding PR https://github.com/learningequality/kolibri/pull/9648
- Read the updated documentation page and preview `KCheckboxes` used in examples …
> KCheckbox: Wrap default's slot content in <label>

- CHANGELOG.md
- docs/pages/filters/index.vue
- docs/pages/kselect.vue
- docs/tableOfContents.js
- lib/KSelect/KeenUiSelect.vue
- lib/KSelect/KeenUiSelectOption.vue
- lib/KSelect/index.vue
- lib/KThemePlugin.js
* Does a minimally modifying port of the KSelect from Kolibri to KDS
* This is almost completely a copy paste + adding to the KThemePlugin, however, some small changes were needed:
* Import paths from KDS were changed to local imports
* KSelect used the `commonCoreStrings` mixin in Kolibri, so this is substituted by having a prop to provide text for the clear action.
* While doing the above, I noticed raw unwrapped text in the component - I replaced this with 'noResultsText` but did not expose it on the KSelect component, because it is currently not used anywhere.
There is almost certainly some refactor that can be done here to avoid the extra component nesting that still exists here, but that seemed better to defer to later for ease of review.
Fixes …
> Add KSelect to KDS.

- CHANGELOG.md
- docs/pages/buttons.vue
- docs/pages/kbutton.vue
- docs/pages/kdropdownmenu.vue
- docs/pages/kiconbutton.vue
- lib/KDropdownMenu.vue
- lib/buttons-and-links/KButton.vue
- lib/buttons-and-links/KIconButton.vue
- lib/buttons-and-links/__tests__/KButton.spec.js
- lib/keen/UiMenuOption.vue
This PR changes the KDropdownMenu API by addressing the issue that KDropdownMenu also contained a button. Now, KDropdownMenu is _only_ the popover elements
Addresses #164
Does a better job fixing #136 (which caused a regression with my last fix). 
Fix the regression where the [additional options for the button (previously in a `<slot/>` in KDropdownMenu is no longer working](https://kolibri-design-system.netlify.app/buttons/#dropdowns), as you can see in the documentation
There are no visual changes to the UI (I hope!)
I will open a corresponding kolibri PR that points to this commit next week with instructions for testing.
The makes `KDropdownMenu` a slot for `KButton` (or `KIconButton`) rather than responsible for also creating the button.
Doing this would require some (fairly …
> Update kdropdown menu api

- CHANGELOG.md
- docs/pages/buttons.vue
- docs/pages/kdropdownmenu.vue
- lib/KDropdownMenu.vue
- lib/buttons-and-links/KButton.vue
https://github.com/learningequality/kolibri-design-system/pull/346 follow-up. It contains a bug fix and some changelog and documentation updates, please see commit messages.
Do the changelog and documentation updates make sense?
> "Update kdropdown menu api #346" follow-up

- lib/KBreadcrumbs.vue
Per conversation on Slack, I've added attributes binding and an aria-label option to `KBreadcrumbs` so that it is easier for us to use a label on the <nav> element, which is where it should be.
1. See [corresponding kolibri PR](https://github.com/learningequality/kolibri/pull/9663) for testing. Successful implementation should have the aria label display on the breadcrumb elements
Is this clear enough? would props be better?
> add attrs/aria-label to navigation element within KBreadcrumbs

- CHANGELOG.md
- docs/assets/main.scss
- docs/pages/kresponsiveelement.vue
- docs/pages/kresponsivewindow.vue
- docs/pages/layout/index.vue
- docs/tableOfContents.js
Updates library documentation:
- Updates _Layouts_ page: Some sections related to  `KResponsiveWindowMixin` were moved to its new page, and _Layouts_ page now only contains general breakpoints information with newly added references to the two new pages. 
- Adds two new pages:
- _KResponsiveWindow_ page: To a large extent, existing documentation from the _Layouts_ page was used.
- _KResponsiveElement_ page: I wrote down some basic information and usage but didn't create an example since it's quite simple, and also, currently, we rather discourage using it.
Two new pages were prepared with keeping https://github.com/learningequality/kolibri-design-system/issues/288 (allow mixins logic to be used via composition API) in mind. Therefore, pages are called …
> Add documentation pages for KResponsiveWindow and KResponsiveElement

- docs/common/DocsShow.vue
- docs/common/DocsShowCode.vue
- docs/common/DocsShowCode/index.vue
- docs/common/DocsShowCode/webpack-loader.js
- docs/pages/colors.vue
- docs/pages/layout/index.vue
- docs/pages/styling/index.vue
- nuxt.config.js
Improves `DocsShowCode` component layout:
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/188290801-47e2fced-2744-4cb7-836f-ac433ff32eb3.png) | ![image](https://user-images.githubusercontent.com/2367265/188290807-7ed3dccb-bf94-4690-ab66-269aa7971050.png) |
Allows example HTML and Vue code to be inserted verbatim, without escape sequences or `eslint-disable` directives:
```diff
-      
-      
<DocsShowCode language="html">
-        &lt;KGrid&gt;
-          &lt;KGridItem :layout12="{ span: 9 }"&gt;
-            &lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit&lt;/h2&gt;
-          &lt;/KGridItem&gt;
-          &lt;KGridItem :layout12="{ span: 3, alignment: 'right' }"&gt;
-            &lt;KButton text="Button" primary/&gt;
- …
```
> updates to DocsShowCode component

- CHANGELOG.md
I'm updating the release process document where I want to mention that our changelog has two sections - one for `develop` branch and another for the current `release` branch so made a little improvement to naming of the `develop` section to make it clearer of which version `develop` updates will eventually be part of
> Better naming of the changelog section

- .github/pull_request_template.md
Removes the "Post-merge updates and tracking" section from the PR template that we currently skip anyways so that it doesn't confuse PRs authors (example https://github.com/learningequality/kolibri-design-system/pull/364).
> Clean up the PR template

- docs/common/DocsShow.vue
- docs/common/DocsShowCode.vue
- docs/common/DocsShowCode/index.vue
- docs/common/DocsShowCode/webpack-loader.js
- docs/pages/colors.vue
- docs/pages/kresponsivewindow.vue
- docs/pages/layout/index.vue
- docs/pages/styling/index.vue
- nuxt.config.js
Backports https://github.com/learningequality/kolibri-design-system/pull/358 to the release branch to avoid troubles with different `DocsShowCode` content syntaxes when merging the release branch to the develop.
> Backport "updates to DocsShowCode component #358" to the release branch

- README.md
You should not have to mess with your package.json to yarn link - this guidance is unnecessary
> Update README.md guidance on link

- docs/pages/layout/index.vue
This fixes `Property or method "windowIsLarge" is not defined on the instance but referenced during render` error that I caused recently when I was moving some parts of documentation from "Layout" page to another pages but didn't notice that I need to preserve the `KResponsiveWindowMixin` on the "Layout" page.
I didn't update the changelog as this is not user-facing but rather an internal docs bugfix.
Unfortunately, I merged the release branch to develop when this bug was still present on the release branch. As I will be offline soon, could someone please do it again once this PR is merged so that it is also fixed on the develop branch?
- Preview "Layouts" page
> Fix missing mixin

- CHANGELOG.md
- lib/styles/trackInputModality.js
Focus inputs of type "password" when navigating using the keyboard.
Fixes issue #9563 from Kolibri repo - "Missing focus ring around password inputs".
Before:
After:
1. Link this updated Kolibri-design-system to the Kolibri repo
2. Start a devserver for the Lolibri repo
3. Create a new account in Kolibri
4. Tab through the inputs using the keyboard and note that an outline is applied to the password inputs
Added a new type of input (password) to the list of keyboard modality default elements.
No
Unsure how to handle the post-merge updates
> Add focus outline to password type inputs when navigating using keyboard

- lib/useKWindowDimensions.js
Incorrect arguments to removeEventListener, adds 'resize' as argument on unmount for window.removeEventListener
#398
> fix add event type in removeEventListener in useKWindowDimension

- README.md
Removes the step that instructs devs to delete the `package.json` reference to KDS when using `yarn link`
Resolves [a problem discussed in Slack](https://learningequality.slack.com/archives/C0LE9NLCE/p1661252757986809?thread_ts=1661167701.303799&cid=C0LE9NLCE) where several team members had trouble with `yarn link` working correctly when deleting this from `package.json`.
> Update documentation to not includedeleting KDS from package.json

- lib/buttons-and-links/KButton.vue
This replace the `<template />` tags which were needed in the `KButton` code in order for the refactored `KDropdownMenu` to work correctly. I think I accidentally dropped them during rebase.
Addresses https://github.com/learningequality/kolibri/issues/9754
Please see corresponding Kolibri PR to test in Kolibri
> Add missing template tags to KButton

- lib/KDateRange/KDateCalendar.vue
- lib/KDateRange/ValidationMachine.js
This PR fixes the incorrect display of the _Month Year_ on the `KDateRange` calendar when the previous month is December of last year and the current month is January. Previously, the left side of the calendar was incorrectly set to December of this year and the right side of the calendar was set to January of next year.
The `font-family` declaration has also been removed from `KDateCalendar` as it was unnecessary and caused implementation issues when `KDateRange` is used in Kolibri. 
Added `predictableActionArguments: true` to xstate validation machine to fix console warning based on XState Docs recommendations found [here](https://xstate.js.org/docs/guides/actions.html).  
Fixes #405 
Before, incorrect _Month Year_ display
After, correct _Month Year_ display
1. Open KDateRange calendar …
> Corrected kdaterange month and year display and removed font-family

- lib/KSelect/KeenUiSelect.vue
- lib/KSelect/KeenUiSelectOption.vue
- lib/KSelect/index.vue
Expose `select` event provided by KeenUISelect.
Addresses #342
Use KSelect component and provide a `@select` event handler. The handler should execute on any select option and should receive the selectedOption, and an options object as first and second argument.
`KeenUISelect` emits an `select` event whenever an option is selected. So it just add a handler to the `KSelect` wrapper to emit the `select` event emitted by `KeenUISelect`.
The `options` argument emitted by the `select` event is just an object with just one boolean property `selected` that indicates whether the selected option was previous selected.
```JSX
<KSelect
...
@select="onSelectHandler"
/>
...
onSelectHandler(newSelection, options) {
console.log(newSelection); // New selected option
console.log(options.selected); // True …
```
> [Kselect] Expose select event

- CHANGELOG.md
- docs/pages/koptionaltext.vue
- docs/tableOfContents.js
- lib/KOptionalText.vue
- lib/KThemePlugin.js
- lib/__tests__/KOptionalText.spec.js
Add a new component to KDS `KOptionalText` that will either display the text or `KEmptyPlacehlder` if it's an empty string, undefined, or null.
Addresses #285
1. Link this KDS branch to any product.
2. Use `KOptionalText` component as described in Implementation notes.
`KOptionalText` will recieve a `text` prop or slot that renders text nodes, if there is text to show, the text or the slot will be shown whithin a `span` element, if not, the `KEmptyPlacehlder` component will be shown. Also a `textStyle` prop can be passed which will be set to the `span` element.
Examples:
All of them will render "Hello world" in red color:
```vue
<KOptionalText text="Hello world" appearanceOverrides="color: red" />
<KOptionalText appearanceOverrides="color: red">
Hello World
<KOptionalText/> …
```
> [KOptionalText] New component

- CHANGELOG.md
- docs/pages/kdaterange.vue
- jest.conf/setup.js
- lib/KDateRange/KDateCalendar.vue
- lib/KDateRange/KDateDay.vue
- lib/KDateRange/KDateInput.vue
- lib/KDateRange/__tests__/KDateRange.spec.js
- lib/KDateRange/index.vue
- package.json
- yarn.lock
This PR updates the `KDateRange` component to use the `vue-intl` `$formatDate` function, which displays the months of the year within the KDateCalendar in the correct language. 
Updated KDateRange component with correct month name displayed for previously unsupported languages:
Burmese - my
#
Georgian - ka
#
Khmer - km
#
Chichewa, Chewa, Nyanja - nyn
#
Fulfulde (Cameroon) - ff-cm
#
Hausa - ha
#
Yoruba - yo
1. Use corresponding PR to test in Kolibri: https://github.com/learningequality/kolibri/pull/10207
2. Change the language to one of the previously mentioned above
3. Navigate to Facility > Data
4. Select Generate Log for either session or summary logs
5. The months should be displayed in the selected language
`$formatDate` function is used within `KDateCalendar` and displays the month …
> Kdaterange date formatting

- CHANGELOG.md
- lib/loaders/KCircularLoader.vue
Accompanying PR to https://github.com/learningequality/kolibri/pull/10558 which, by means of two new props `show` and `freeze`, adds an option to prevent the loader from hiding for the chosen amount of time even when the condition for displaying it (e.g. "is the request still processing?") is not truthy anymore. Example:
```vue
<KCircularLoader
:show="shouldShow"
:freeze="3000"
/>
```
means that the loader component will be displayed for 3 seconds even when `shouldShow` is falsy sooner than 3s.
This is to prevent the loader from appearing and disappearing very fast (see `props` comments to understand how this is different from the `delay` prop)
It's used in https://github.com/learningequality/kolibri/pull/10558. When you click the download button on a remote content page, the loader will …
> Add an option to freeze loader

- CHANGELOG.md
- docs/pages/kdaterange.vue
- docs/plugins/load-lib-components.js
- lib/KDateRange/KDateCalendar.vue
- lib/KDateRange/KDateDay.vue
- lib/KDateRange/KDateInput.vue
- lib/KDateRange/ValidationMachine.js
- lib/KDateRange/__tests__/KDateInput.spec.js
- lib/KDateRange/__tests__/KDateRange.spec.js
- lib/KDateRange/__tests__/ValidationMachine.spec.js
- lib/KDateRange/index.vue
- lib/KDateRange/validationConstants.js
This pull request updates the component KDateRage to use input[type=date] to allow for the use of browser placeholders for language translation in Kolibri.
Closes #442 
Before; Italian
After:
Italian
Arabic
English (UK)
See this [Kolibri pull request](https://github.com/learningequality/kolibri/pull/10987) for testing.
1. In Kolibri, navigate to Facility > Data page
2. Make sure there are no previously generated session or summary logs
3. Change language in Kolibri to something other than English
4. *May have to change language in system settings as well*
- Removed validation constant `DATE_FMT` (DD/MM/YYYY)
- Set validation machine start and end date values to null instead of `DATE_FMT`
- Updated validation machine error handling
- Changed input type to date inside `KDateInput` component …
> Update KDateRange to use input[type=date]

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
- dev_docs/01_getting_started.md
- dev_docs/02_tips_and_troubleshooting.md
- dev_docs/03_how_to_update_library.md
- dev_docs/04_how_to_update_docs.md
- dev_docs/05_icons.md
- dev_docs/06_misc.md
- docs/pages/playground.vue
This is a sibling to Kolibri's PR https://github.com/learningequality/kolibri/pull/11096 and part of larger efforts to make our issues better discoverable, documentation more friendly, and in the case of KDS also easier development process of components for contributors and any newcomers to this repository.
- Adds CONTRIBUTING.md and updates README.md to contain only necessary information and a copy of contributing guidelines for better discoverability. Both files now have the same structure as Kolibri's CONTRIBUTING and README (Studio to come).
- Moves most of the README's content into `dev_docs` folder and organizes it in to more files while focusing on
- friendliness and clarity
- information organized by focusing on necessary steps at first and providing links to more detailed …
> Make KDS contributor friendly

- CHANGELOG.md
- docs/pages/kcircularloader.vue
- docs/pages/ktransition.vue
- docs/pages/usekshow.vue
- docs/tableOfContents.js
- lib/KThemePlugin.js
- lib/KTransition.vue
- lib/composables/useKShow.js
- lib/loaders/KCircularLoader.vue
- Extracts the logic for displaying loader for a minimum amount of time from `KCircularLoader` to a new `useKShow` composable to allow for usage in v-if/v-else blocks and with any component
- Relatedly renames `KCircularLoader`'s `show` prop to `shouldShow` to prevent from naming conflicts
- Adds a documentation sidebar section for all composables and adds the documentation for `useKShow` there
- Adds pieces of guidance to docs on when to use `useKShow` vs `KCircularLoader`'s `minVisibleTime`
- Adds an option to disable the default `KCircularLoader`'s transition to prevent from glitches when using the loader in tandem with another component, both of them wrapped in a transition
- Adds a new component `KTransition` as a beginning of journey towards having a limited set of consistently used …
> Add supporting code for Kolibri loaders

- .github/workflows/changelog.yml
- CHANGELOG.md
- lib/KTextbox/index.vue
This change will not allow the input fields(Which has preprocessed input) of any page to appear focused when navigated with keyboard.
I have described the problem in this[ comment](https://github.com/learningequality/kolibri/issues/9077#issuecomment-1717541887)
Fixes: #[9077](https://github.com/learningequality/kolibri/issues/9077)
Before
[Screencast from 15-09-23 04:49:34 PM IST.webm](https://github.com/learningequality/kolibri-design-system/assets/120925871/7322c415-d412-4846-bc9b-cd6e8b3a1074)
After:
[Screencast from 15-09-23 04:46:38 PM IST.webm](https://github.com/learningequality/kolibri-design-system/assets/120925871/6c01cdf6-651a-442b-96a9-fa23c6167c22)
> removed updation of style while text updates

- CHANGELOG.md
- lib/tabs/__tests__/KTabsPanel.spec.js
- lib/useKResponsiveWindow/__tests__/useKResponsiveWindow.spec.js
- lib/useKResponsiveWindow/index.js
- lib/useKWindowDimensions.js
this PR fixes a bug observed during QA review of Kolibri in `Learn` > `Library` - in certain cases, rapidly resizing the browser window would cause the sidepanel to automatically display when the screen was small, behavior we did not expect nor want at that screen size. beneath the surface, the components were receiving conflicting information about the current screen size because `useKResponsiveWindow` was not updating in the way we expected. 
to address those issues, this PR introduces changes to the scope of variables within `useKResponsiveWindow` and to the way the composable uses `useKWindowDimensions`. 
[reported as a Kolibri issue ](https://github.com/learningequality/kolibri/issues/11212)
BEFORE, courtesy of @pcenov:
https://github.com/learningequality/kolibri/assets/79847249/0b63d …
> useKResponsiveWindow update fixing resizing behavior in Learn > Library

- CHANGELOG.md
- docs/common/DocsInternalLink.vue
- docs/pages/icons/index.vue
- docs/pages/kicon.vue
- docs/pages/kmodal.vue
- docs/pages/kselect.vue
- docs/pages/ktextbox.vue
- add validator for internal link URLs
- fix broken links
Follow-up from https://github.com/learningequality/kolibri-design-system/pull/423
Many instances of `DocsInternalLink` were broken on the Netlify deployed site. This wasn't obvious because the links worked fine from the dev server. The difference is because Netlify adds a trailing slash to all URLs:
https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash
Found instances with regex: `<DocsInternalLink(.|\n)*?href="[^/]`
|--|--|
| ![2023-10-04 06 54 54](https://github.com/learningequality/kolibri-design-system/assets/2367265/4096c689-87c7-4c23-bc80-4930369327ef) | ![2023-10-04 06 59 56](https://github.com/learningequality/kolibri-design-system/assets/2367265/043ca66a-2c41-49ed-a341-280958923841) …
> fix broken internal links

- CHANGELOG.md
- Fixes missing links to PRs
- Fixes version
- Adds a new section for the upcoming version
> Prepare changelog for the new release

- CHANGELOG.md
- lib/KResponsiveWindowMixin.js
This PR consoles a warning when `KResponsiveWindow` mixin is used instead of `useKResponsive`
Addresses #459
> Warning when using `KResponsiveWindow`

- CHANGELOG.md
- lib/__tests__/useKWindowDimensions.spec.js
- lib/useKResponsiveWindow/__tests__/useKResponsiveWindow.spec.js
- lib/useKWindowDimensions.js
fixes #461
I also linked this with Kolibri and tested this out, and It seems to be working fine for me.
> debounced updateWindow

- CHANGELOG.md
- lib/useKResponsiveWindow/MediaQuery.js
* Adds an additional guard to prevent attempting to access the window.matchMedia API when it is in an environment that it is not supported
* Fixes a hitherto unnoticed bug, whereby the use of a JS getter to return the value of window.matchMedia meant that removing event listeners was doing nothing, as the getter was returning a new instance each time (and so was not unbinding the listener from the instance that it had actually been bound to).
* Does this by caching the window.matchMedia result call, to minimize code changes and to continue to allow delay of instantiation of the mediaQueryList object.
Fixes failing tests seen in develop on Kolibri
Fixes unreported bug that would stop listeners from being unbound
> Match media testing guard and bug fix

- CHANGELOG.md
- package.json
Changed command name from _dev-only to dev-only for easiness.
Fixes #474
> Changed _dev-only to dev-only

- CHANGELOG.md
- lib/__tests__/useKWindowDimensions.spec.js
- lib/useKResponsiveWindow/__tests__/useKResponsiveWindow.spec.js
This PR replaces the use of setTimeout() in unit tests for useKWindowDimensions and useKResponsiveWindow with the use of requestAnimationFrame to eliminate test flakiness caused by inconsistency in setTimeout execution.
Addresses #480 
- [#491]
- **Description:** Replaced setTimeout with requestAnimationFrames in tests for useKWindowDimensions and useKResponsiveWindow
- **Products impact:** -
- **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/480
- **Components:** none
- **Breaking:** no
- **Impacts a11y:** no
[#491]: [https://github.com/learningequality/kolibri-design-system/pull/491]
1. in `/kolibri-design-system/lib` run `yarn test` 
Replace setTimeout with requestAnimationFrames in related tests
no
requestAnimationFrame eliminates the …
> use requestAnimationFrame instead of setTimeout

- .github/workflows/changelog.yml
- CHANGELOG.md
#481 
- [#505]
- **Description:**  Added custom implementation of GH action that checks that changelog is updated in each pull request
- **Products impact:** 
- **Addresses:** -
- **Components:** -
- **Breaking:** 
- **Impacts a11y:** 
[#505]: https://github.com/learningequality/kolibri-design-system/pull/505
> Added custom implementation of GH Action

- CHANGELOG.md
- lib/KImg.vue
`KImg` now emits the 'error' event when an error is encountered while loading the image specified in src with the `event` parameter that can be used by the clients. 
Fixes #372 
- [#502]
- **Description:** Add dispatching of 'error' event when failed to load image for 'KImg'
- **Products impact:** new API
- **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/372
- **Components:** KImg
- **Breaking:** no
- **Impacts a11y:** yes  
- **Guidance:** Allows the consumer to hook into the lifecycle of 'KImg' and handle the cases when the image fails to load
[#502]: https://github.com/learningequality/kolibri-design-system/pull/502
Used the `@error` provided by `Vue` and declared a new event `error`
No
> feat: add `onError` handler for `KImg`

- CHANGELOG.md
- docs/pages/kimg.vue
- lib/KImg.vue
Adds the `appearanceOverrides` prop to `KImg` component for styling
Fixes #371  
- [#509]
- **Description:** Introduces `appearanceOverrides` prop for the `KImg` component
- **Products impact:** new API 
- **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/371
- **Components:** KImg
- **Breaking:** No
- **Impacts a11y:** Yes
- **Guidance:** Adds a way to style the component intrinsically, allowing users to make more a11y compatible components
[#509]: https://github.com/learningequality/kolibri-design-system/pull/509
I added a new prop to the component and then passed its styles to the `styleObject`.
No
> feat: add `appearanceOverrides` prop to `KImg`

- .github/pull_request_template.md
- CHANGELOG.md
- package.json
- yarn.lock
- Removes unused `keen-ui` dependency
- I also added a small fix to changelog item link format
- [#531]
- **Description:** Remove unused `keen-ui` dependency
- **Products impact:** none
- **Addresses:** -
- **Components:** -
- **Breaking:** -
- **Impacts a11y:** -
[#531]: https://github.com/learningequality/kolibri-design-system/pull/531
You could confirm that the dependency is indeed not used from anywhere.
> Remove unused keen-ui dependency

- .htmlhintrc.js
- .stylelintrc.js
- docs/pages/icons/index.vue
- lib/KDateRange/KDateInput.vue
- lib/KSelect/index.vue
* Removes two unused /deep/ selectors in KSelect that were referencing non-existent classes
* Replaces the two remaining /deep/ selectors used in KDS with `::v-deep` https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors
* This behaves identically, but has the advantage of not breaking future versions of Sass (i.e. Dart Sass instead of Node Sass, which is deprecated)
This is required as part of an extended yak shave in order to ultimately upgrade to newer NodeJS versions, where building Node Sass becomes increasingly more challenging.
- **Description:** Remove use of /deep/ in favour of ::v-deep
- **Products impact:** none
- **Addresses:** -
- **Components:** -
- **Breaking:** no
- **Impacts a11y:** -
1. Ensure that KSelect still functions as intended when …
> /deep/ to ::v-deep
